apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2 # Set your desired number of replicas
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret # Reference your GitLab registry secret here
      containers:
        - name: myapp-container
          image: "registry.gitlab.com/eli3623142/circleci:94-1c37cd7d89c20876125e9ef0c2a391432ed07c3e" # Use your GitLab image
          ports:
            - containerPort: 8000 # Port your container listens on
