name: Delete Resources

on:
  repository_dispatch:
    types: [delete]

jobs:
  delete-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Payload
        run: |
          echo "Namespace: ${{ github.event.client_payload.namespace }}"

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Get Listener ARNs by ALB ARN
        id: get-listeners
        run: |
          ALB_ARN="${{ secrets.ALB_ARN }}"
          LISTENERS=$(aws elbv2 describe-listeners --load-balancer-arn "$ALB_ARN" --query 'Listeners[*].ListenerArn' --output text)
          
          if [ -z "$LISTENERS" ]; then
            echo "No listeners found for load balancer $ALB_ARN."
            exit 1
          fi

          echo "LISTENERS=$LISTENERS" >> $GITHUB_ENV

      - name: Get Security Group ID
        id: get-security-group
        run: |
          ALB_ARN="${{ secrets.ALB_ARN }}"
          SECURITY_GROUP_ID=$(aws elbv2 describe-load-balancers --load-balancer-arns "$ALB_ARN" --query 'LoadBalancers[0].SecurityGroups[0]' --output text)
          echo "SECURITY_GROUP_ID=$SECURITY_GROUP_ID" >> $GITHUB_ENV

      - name: Delete Security Group Ingress for All Listener Ports
        run: |
          SECURITY_GROUP_ID="${{ env.SECURITY_GROUP_ID }}"
          LISTENERS="${{ env.LISTENERS }}"
          PORTS=$(aws elbv2 describe-listeners --listener-arns $LISTENERS --query 'Listeners[*].Port' --output text)

          if [ "$SECURITY_GROUP_ID" != "None" ]; then
            for PORT in $PORTS; do
              aws ec2 revoke-security-group-ingress --group-id "$SECURITY_GROUP_ID" --protocol tcp --port "$PORT" --cidr 0.0.0.0/0 || echo "Ingress rule for port $PORT not found."
            done
          else
            echo "No Security Group found for the ALB."
          fi

      - name: Delete Listeners
        run: |
          LISTENERS="${{ env.LISTENERS }}"
          for LISTENER in $LISTENERS; do
            aws elbv2 delete-listener --listener-arn "$LISTENER" || echo "Failed to delete listener $LISTENER."
          done

      - name: Delete Argo CD Application
        run: |
          NAMESPACE="${{ github.event.client_payload.namespace }}"
          APP_NAME="${NAMESPACE}-app"
          argocd login "${{ secrets.ARGOCD_SERVER }}" --username "${{ secrets.ARGOCD_USERNAME }}" --password "${{ secrets.ARGOCD_PASSWORD }}" --insecure
          argocd app delete "$APP_NAME" --cascade --yes

      - name: Delete Kubernetes Namespace
        run: |
          NAMESPACE="${{ github.event.client_payload.namespace }}"
          kubectl delete namespace "$NAMESPACE"

      - name: Final message
        run: echo "Resources for namespace ${{ github.event.client_payload.namespace }} have been deleted."
